require("dotenv").config();
const axios = require("axios");
const { readFileSync, writeFileSync } = require("fs");
const { join } = require("path");

const README = join(__dirname, "README.md");
const AUTOGENERATED_MARKER = "<!-- autogenerated -->";

const getUploadVideos = async () => {
  const config = {
    headers: {
      Accept: "application/json",
    },
  };

  const API_KEY = process.env.API_KEY;
  const UPLOAD_ID = "UUiRPKet-kWNqoBjbse7WD2g";

  const url = `https://youtube.googleapis.com/youtube/v3/playlistItems?part=snippet&playlistId=${UPLOAD_ID}&key=${API_KEY}`;

  const { data } = await axios.get(url, {}, config);
  const { items } = data;
  return items;
};

const updateREADME = async () => {
  const videosResponse = await getUploadVideos();

  const readmeContent = readFileSync(README, "UTF-8");

  let updatedREADME = readmeContent.substring(
    0,
    readmeContent.indexOf(AUTOGENERATED_MARKER) + AUTOGENERATED_MARKER.length
  );

  updatedREADME += videosResponse.reduce((accumulator, current) => {
    const { snippet } = current;
    const { title, resourceId } = snippet;
    const { videoId } = resourceId;
    const link = `https://youtu.be/${videoId}`;

    let listItem = `<li><a href="${link}">${title}</a></li>`;

    return `${accumulator} ${listItem}\n`;
  }, "\n\n");

  writeFileSync(README, updatedREADME);
};
updateREADME();
