const { readFileSync, writeFileSync } = require("fs");
const { join } = require("path");
const JSSoup = require("jssoup").default;
const request = require("request");

const README = join(__dirname, "README.md");
const AUTOGENERATED_MARKER = "<!-- autogenerated -->";

const sync = async () => {
  request.get(
    "https://www.youtube.com/c/IsaacFrank/videos",
    (err, res, html) => {
      let soup = new JSSoup(html);
      let scriptContent = soup.find("body").findAll("script")[1].contents[0]
        ._text;

      scriptContent = scriptContent.replace(`window["ytInitialData"] = `, "");
      scriptContent = scriptContent.replace(
        `window["ytInitialPlayerResponse"] = null;`,
        ""
      );
      scriptContent = scriptContent.replace(`if (window.ytcsi) {`, "");
      scriptContent = scriptContent.replace(`;`, "");
      scriptContent = scriptContent.replace(
        `window.ytcsi.tick("pdr", null, '');}`,
        ""
      );
      let allTabs = JSON.parse(scriptContent).contents
        .twoColumnBrowseResultsRenderer.tabs;
      let videos = [];
      for (let index = 0; index < allTabs.length; index++) {
        const element = allTabs[index];
        if (element.tabRenderer.title == "Videos") {
          videos = element.tabRenderer.content.sectionListRenderer.contents[0].itemSectionRenderer.contents[0].gridRenderer.items
            .slice(0, 5)
            .map((entry) => ({
              title: entry.gridVideoRenderer.title.runs[0].text,
              url: `https://youtu.be/${entry.gridVideoRenderer.videoId}`,
            }));
          break;
        }
      }
    }
  );

  const readmeContent = readFileSync(README, "utf-8");

  let updatedReadmeContent = readmeContent.substring(
    0,
    readmeContent.indexOf(AUTOGENERATED_MARKER) + AUTOGENERATED_MARKER.length
  );
  updatedReadmeContent += latestPosts.reduce(
    (acc, post) => `${acc}- [${post.title}](${post.url})\n`,
    "\n\n"
  );

  writeFileSync(README, updatedReadmeContent);
};

sync().catch((error) => console.error(error));
